name: Check backend code

on:
  push:
    branches: ["main"]

jobs:
  update-hosts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        host:
          - nixnest.bushbaby-chimera.ts.net

    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: NodeJS version
        run: node --version
      - name: Tailscale join
        uses: https://github.com/tailscale/github-action@v4
        continue-on-error: true
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:cicd
          version: latest
          use-cache: "false"
          tailscaled-args: --verbose

      - run: cat ~/tailscale.log
      - name: Test connectivity
        run: |
          # Test that we can reach the Tailscale network
          tailscale status

          # Show our IP address
          tailscale ip

      - name: Tailscale ping
        uses: https://github.com/tailscale/github-action@v4
        with:
          ping: ${{ matrix.host }}

      - run: echo "Updating host ${{ matrix.host }}"
      - run: curl -v -X POST --no-buffer http://${{ matrix.host }}:36196/update
