name: Build packages

on:
  push:
    branches: ["main"]
    paths-ignore:
      - .build-paths.json

jobs:
  update-hosts:
    runs-on: alpine-x86_64-linux
    container:
      volumes:
        - /nix:/nix:ro
    environment:
      NIX_REMOTE: daemon

    steps:
      # TODO: probably needs to checkout all submodules as well
      - run: |
          apk add nix git -q
          echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      - uses: actions/checkout@v7
      - run: |
          git submodule init
          git -c "submodule.secret-nix-config.url=https://x-access-token:${{ secrets.TOKEN }}@git.byte-sized.fyi/emilia/secret-nix-config.git" submodule update --recursive    
          export NIX_REMOTE=daemon

          nix flake metadata
          nix run github:Mic92/nix-fast-build -- --flake .#packages.x86_64-linux --skip-cached --out-link result
          cp result-build-paths .build-paths.json

          git status
          git add .build-paths.json
          git config user.name "byte-sized.fyi Forgejo Instance"
          git config user.email "forgejo@byte-sized.fyi"
          git commit -m ":white_check_mark: (CI) Update .build-paths.json [skip ci]"
          git push
