{ pkgs, ... }:
let
  smartdNtfy = pkgs.writeShellScript "smartd-ntfy" ''
    curl -Ls -H "Title: $SMARTD_SUBJECT" -d "$SMARTD_FAILTYPE Device: $SMARTD_DEVICE Time: $SMARTD_TFIRST Message: $SMARTD_FULLMESSAGE" https://ntfy.service.byte-sized.fyi/alerts
  '';
  smartdConf = pkgs.writeText "smartd.conf" ''
    # Autogenerated smartd startup config file
    DEVICESCAN -a -s S/../../7/01 -m <nomailer> -M exec ${smartdNtfy} -M test
  '';
in
{
  systemd.services.smartd = {
    description = "S.M.A.R.T. Daemon";
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "notify";
      ExecStart = "${pkgs.smartmontools}/sbin/smartd --no-fork --configfile=${smartdConf}";
    };
  };
}
