{
  den.aspects.nixdort.nixos =
    { http-services, pkgs, ... }:
    let
      ntfy-service = builtins.head (builtins.filter (s: s.service_name == "ntfy") http-services);

      smartdNtfy = pkgs.writeShellScript "smartd-ntfy" ''
        ${pkgs.curl}/bin/curl -Ls -H "Title: $SMARTD_SUBJECT" -d "$SMARTD_FAILTYPE Device: $SMARTD_DEVICE Time: $SMARTD_TFIRST Message: $SMARTD_FULLMESSAGE" ${ntfy-service.url}/alerts
      '';
      smartdConf = pkgs.writeText "smartd.conf" ''
        # Autogenerated smartd startup config file
        DEVICESCAN -a -s S/../../7/01 -m <nomailer> -M exec ${smartdNtfy} -M test
      '';
    in
    {
      systemd.services.smartd = {
        description = "S.M.A.R.T. Daemon";
        wantedBy = [ "multi-user.target" ];
        serviceConfig = {
          Type = "notify";
          ExecStart = "${pkgs.smartmontools}/sbin/smartd --no-fork --configfile=${smartdConf}";
        };
      };
    };
}
