{
  environment.etc = {
    "certs/self_signed.pem".text = ''
      -----BEGIN CERTIFICATE-----
      MIIBdTCCASegAwIBAgIUZYGC+2p7KquDB01WDWdKsc/YM5owBQYDK2VwMBkxFzAV
      BgNVBAMMDmJ5dGUtc2l6ZWQuZnlpMB4XDTI2MDQxMzEzNTIwNFoXDTM2MDQxMDEz
      NTIwNFowGTEXMBUGA1UEAwwOYnl0ZS1zaXplZC5meWkwKjAFBgMrZXADIQC9A2E0
      hRvsIQShESzGzBvrLShxh988gLXkBvY8YTD326OBgDB+MB0GA1UdDgQWBBSlCRCO
      IrIM9m0eu9tDBMXaTKQ0PzAfBgNVHSMEGDAWgBSlCRCOIrIM9m0eu9tDBMXaTKQ0
      PzAPBgNVHRMBAf8EBTADAQH/MCsGA1UdEQQkMCKCDmJ5dGUtc2l6ZWQuZnlpghAq
      LmJ5dGUtc2l6ZWQuZnlpMAUGAytlcANBADQmZXkcCdrC1C50BjbKRJ5PqlqeEfKW
      uH8hegpD4IvaXEblPHyhEh8gqpchtD20cHhzWRzgkPtGgGx8vwx8xQk=
      -----END CERTIFICATE-----
    '';
    "certs/wildcard_origin_cert.pem".text = ''
      -----BEGIN CERTIFICATE-----
      MIIDJzCCAs6gAwIBAgIUL915GBgZS0pFH1K9Aprw4qJMn6UwCgYIKoZIzj0EAwIw
      gY8xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
      YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBDbG91ZEZsYXJlLCBJbmMuMTgwNgYDVQQL
      Ey9DbG91ZEZsYXJlIE9yaWdpbiBTU0wgRUNDIENlcnRpZmljYXRlIEF1dGhvcml0
      eTAeFw0yNjA0MTMwOTE1MDBaFw00MTA0MDkwOTE1MDBaMGIxGTAXBgNVBAoTEENs
      b3VkRmxhcmUsIEluYy4xHTAbBgNVBAsTFENsb3VkRmxhcmUgT3JpZ2luIENBMSYw
      JAYDVQQDEx1DbG91ZEZsYXJlIE9yaWdpbiBDZXJ0aWZpY2F0ZTBZMBMGByqGSM49
      AgEGCCqGSM49AwEHA0IABBv7n1bLBGtNCG7Q+n8fFbbdvhu2tdwoMqLyj7ikk9ZZ
      TtLOsVsJks6S2SzzmQUo48Eazd3oM14COaEFTTcAfiSjggEyMIIBLjAOBgNVHQ8B
      Af8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMAwGA1UdEwEB
      /wQCMAAwHQYDVR0OBBYEFBYv84wFifDoNlqi1wditDn2cyxPMB8GA1UdIwQYMBaA
      FIUwXTsqcNTt1ZJnB/3rObQaDjinMEQGCCsGAQUFBwEBBDgwNjA0BggrBgEFBQcw
      AYYoaHR0cDovL29jc3AuY2xvdWRmbGFyZS5jb20vb3JpZ2luX2VjY19jYTArBgNV
      HREEJDAighAqLmJ5dGUtc2l6ZWQuZnlpgg5ieXRlLXNpemVkLmZ5aTA8BgNVHR8E
      NTAzMDGgL6AthitodHRwOi8vY3JsLmNsb3VkZmxhcmUuY29tL29yaWdpbl9lY2Nf
      Y2EuY3JsMAoGCCqGSM49BAMCA0cAMEQCIBUENOuSNv2DkU4GM9Gh6KcvkOmXhj0A
      jPeRXDy0iFBUAiAF55Bnmw+p8+VZUl0dJol9qernVpcR7g5vQ2zHNO/d/A==
      -----END CERTIFICATE-----
    '';
    "certs/links_byte_sized_fyi_origin_cert.pem".text = ''
      -----BEGIN CERTIFICATE-----
      MIIDLTCCAtKgAwIBAgIUc8zGQifPlR1ZclYkd5MzOkERaMEwCgYIKoZIzj0EAwIw
      gY8xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
      YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBDbG91ZEZsYXJlLCBJbmMuMTgwNgYDVQQL
      Ey9DbG91ZEZsYXJlIE9yaWdpbiBTU0wgRUNDIENlcnRpZmljYXRlIEF1dGhvcml0
      eTAeFw0yNjAyMjAxNDUxMDBaFw00MTAyMTYxNDUxMDBaMGIxGTAXBgNVBAoTEENs
      b3VkRmxhcmUsIEluYy4xHTAbBgNVBAsTFENsb3VkRmxhcmUgT3JpZ2luIENBMSYw
      JAYDVQQDEx1DbG91ZEZsYXJlIE9yaWdpbiBDZXJ0aWZpY2F0ZTBZMBMGByqGSM49
      AgEGCCqGSM49AwEHA0IABPgvNqn781jlLzyroCLNvxL7d15Ed1W5KE36nCJcp/8R
      k6LpJtYSnI8Do2s0DSkunnf1WoEHuqQsbhR6cpApoA2jggE2MIIBMjAOBgNVHQ8B
      Af8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMAwGA1UdEwEB
      /wQCMAAwHQYDVR0OBBYEFEn2xV4Zi1nojY8QQ1nypjecvKGdMB8GA1UdIwQYMBaA
      FIUwXTsqcNTt1ZJnB/3rObQaDjinMEQGCCsGAQUFBwEBBDgwNjA0BggrBgEFBQcw
      AYYoaHR0cDovL29jc3AuY2xvdWRmbGFyZS5jb20vb3JpZ2luX2VjY19jYTAvBgNV
      HREEKDAmgg5ieXRlLXNpemVkLmZ5aYIUbGlua3MuYnl0ZS1zaXplZC5meWkwPAYD
      VR0fBDUwMzAxoC+gLYYraHR0cDovL2NybC5jbG91ZGZsYXJlLmNvbS9vcmlnaW5f
      ZWNjX2NhLmNybDAKBggqhkjOPQQDAgNJADBGAiEAlnleoj/Yqkw7HH+Ybq1mJ0IN
      sJXxlW14szH+xolycQwCIQCOKYZrwPd+ECxCd22Oo8dsi0oFmfrOzySU/gTvGBG2
      9Q==
      -----END CERTIFICATE-----
    '';
  };
}
